### ISSUE TITLE
As a requester, I want to be able to choose more than 1 helper among all the people who decided to accept my favor, so that I can choose the one who fits best my needs

### ISSUE THREAD

**Issue by danielpgp1012** [favo-sdp/Favo#19]

**Comment by mikanikos** [comment]
This is actually not closed because it's slightly different from what we currently have, the idea is basically accepting more than one user who committed to do the favor. Let's discuss it during the meeting though.

**Comment by mikanikos** [comment]
Closing after changing the title. I'll create another one for the thing I was mentioning in the previous comment.
