### ISSUE TITLE
I don't want to get the wrong notification when I commit a favor.

### ISSUE THREAD

**Issue by huajian1069** [favo-sdp/Favo#246]

**Comment by mikanikos** [comment]
Can you provide some details on how to reproduce the issue?

**Comment by huajian1069** [comment]
when a user commits a favor, both requester and committed user will get a notification saying: this favor has been modified.  This is true because the userIds field is modified when committed user put his userId into the userIds list of favor.

**Comment by mikanikos** [comment]
Ok I see the problem, when implementing the new feature we didn't modify notifications accordingly. I'll look into it in the next days
