### ISSUE TITLE
Hamburger menu background disappears sometimes

### ISSUE THREAD

**Issue by danielpgp1012** [favo-sdp/Favo#263]
![image](https://user-images.githubusercontent.com/24901509/83327968-2d6f3d80-a280-11ea-8cf4-1a7d395ce86a.png)

**Comment by mikanikos** [comment]
I know why, the background of the hamburger menu is hidden when using the map view for choosing the location on favor request. I'll take care of this.

**Comment by mikanikos** [comment]
Unless we want to remove the background circle completely, even without that the hamburger icon doesn't look so bad.
