### ISSUE TITLE
I am not able to access my account after clicking the link in the email. I should be able to log in even if I don't open the email from the same device that launched the application.

### ISSUE THREAD

**Issue by danielpgp1012** [favo-sdp/Favo#48]

**Comment by mikanikos** [comment]
I don't think this is doable. Clicking on the email link launches an intent that should be catched by our app and make the login possible, so there's no way to login by clicking on the link on another device.

On the other hand, normal email link sign-in o the same device works for me. If there are any issues with that, please re-open the issue.
